---
gcp_project: sandbox-173316
gcp_auth_kind: serviceaccount
gcp_service_account_file: ~/.apigee-secure/sandbox-1f5fb288d552.json
gcp_zone: "us-central1-c"
gcp_region: "us-central1"
network_name: "apigeenetwork"
name_instance: "apigee"
name_instance_network_tag: "{{ name_instance }}-network-tag"
name_firewall: "{{ name_instance }}-firewall"
name_address: "{{ name_instance }}-address"
name_disk: "{{ name_instance }}-disk"
scope_compute: "https://www.googleapis.com/auth/compute"
image_project: 'centos-cloud'
#image_project: 'ubuntu-os-cloud'
image_family: 'centos-7'
#image_family: 'ubuntu-1604-lts'
disk_source_image: "projects/{{ image_project }}/global/images/family/{{ image_family }}"
disk_size: 50
bastion_disk_size: 20
machine_type: n1-standard-1
gce_image: 'centos-7'
service_account_email: "friasc@sandbox-173316.iam.gserviceaccount.com"

firewall_ports:
- { ports: "{{ ms_ports }}", port_type: 'ms' }
- { ports: "{{ router_ports }}", port_type: 'router' }
- { ports: "{{ mp_ports }}", port_type: 'mp' }
- { ports: "{{ zk_ports }}", port_type: 'zk' }
- { ports: "{{ cassandra_ports }}", port_type: 'cs' }
- { ports: "{{ qpid_ports }}", port_type: 'qs' }
- { ports: "{{ pg_ports }}", port_type: 'pg' }
- { ports: "{{ ui_ports }}", port_type: 'ui' }
- { ports: "{{ ldap_ports }}", port_type: 'ldap' }

address_types:
- 'ms'
- 'router'
