---
- include: configuration/update-user.yml
  vars:
    hosts: '{{ hosts }}'
    user: 'root'
  tags:
  - root-user

- hosts: '{{ hosts }}'
  become: yes
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: Install system packages
    yum:
      name: '{{ item }}'
      state: present
    with_items:
    - python-devel
    - openssl-devel
    - libffi-devel
    - gcc
    - vim
    - git
    - elasticache-auto-discovery
    when: ansible_os_family | lower == 'redhat'

  - name: Install pip
    easy_install:
      name: pip
      state: latest

  - name: Install ansible
    pip:
      name: '{{ item }}'
      state: latest
    register: result
    with_items:
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1
    - ansible

  - name: Install ansible playbook setup
    become: no
    git:
      repo: https://github.com/carlosfrias/apigee-opdk-playbook-setup-ansible.git
      dest: ~/apigee-workspace/apigee-opdk-playbook-setup-ansible

  - name: Configure ansible playbook setup
    become: no
    shell: 'ansible-playbook setup.yml'
    args:
      chdir: ~/apigee-workspace/apigee-opdk-playbook-setup-ansible

  - name: Configure ansible playbook setup - ec2
    become: no
    shell: 'ansible-playbook setup-ec2.yml'
    args:
      chdir: ~/apigee-workspace/apigee-opdk-playbook-setup-ansible
