---
- name: Create infrastructure
  hosts: localhost
  vars_prompt:
    - name: project_path
      prompt: "Which project do you want to build? ['5-node','aio','dev','prod']"
      default: "5-node"
      private: no

    - name: default_region
      prompt: "Default Region"
      default: "us-east1"
      private: no

    - name: default_zone
      prompt: "Default Zone"
      default: "us-east1-b"
      private: no

    - name: gcp_credentials_file
      prompt: "Service Account Credentials File Path"
      default: "{{ '~/.apigee-secure/sandbox-1f5fb288d552.json' | expanduser }}"
      private: no

    - name: gcp_project_name
      prompt: "GCP Project Name"
      default: "sandbox-173316"
      private: no

    - name: service_account_email
      prompt: "Service Account Email"
      default: "736255665193-compute@developer.gserviceaccount.com"
      private: no

  vars:
    terraform_state_file: "{{ playbook_dir }}/terraform.tfstate"
#    terraform_workspace: ".terraform"
    terraform_workspace: "{{ playbook_dir }}"
    terraform_version: "0.12.0"
    terraform_download_links:
      Debian: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
      MacOSX: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip"

  tasks:
    - name: Install archive management packages
      become: true
      package:
        name: "unzip"
        state: present
      when: ansible_distribution != "MacOSX"

    - name: Install archive management packages on Mac
      package:
        name: "unzip"
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Set terraform link
      set_fact:
        terraform_download_link: "{{ terraform_download_links[ansible_distribution] }}"

    - name: Download Terraform binary
      get_url:
        url: "{{ terraform_download_link }}"
        dest: "./{{ terraform_download_link | basename }}"
        validate_certs: no

    - name: Unarchive terraform binary
      unarchive:
        src: "{{ terraform_download_link | basename }}"
        dest: ./
        remote_src: yes
#
#    - name: Create workspace folder
#      shell: "{{ playbook_dir }}/terraform init"

#    - name: Initialize terraform state file
#      terraform:
#        binary_path: "{{ playbook_dir }}/terraform"
#        project_path: "{{ playbook_dir }}/{{ project_path }}"
#        state: planned
#        force_init: 'yes'
##        workspace: "{{ terraform_workspace }}"
#        plan_file: "{{ terraform_state_file }}"
#        variables:
#          region: "{{ default_region }}"
#          zone: "{{ default_zone }}"
#          credentials_file: "{{ gcp_credentials_file }}"
#          gcp_project_name: "{{ gcp_project_name }}"

    - name: Create infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ project_path }}"
        state: present
#        state_file: "{{ terraform_state_file }}"
#        plan_file: "{{ terraform_state_file }}"
#        workspace: "{{ terraform_workspace }}"
        variables:
          region: "{{ default_region }}"
          zone: "{{ default_zone }}"
          credentials_file: "{{ gcp_credentials_file }}"
          gcp_project_name: "{{ gcp_project_name }}"