---
- name: Update Cache for validate config file generation
  hosts: planet
  tags: ['setup', 'cleanup']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
    - { role: apigee-opdk-settings-private-address  }
    - { role: apigee-opdk-settings-management-server  }
    - { role: apigee-opdk-settings-region }

- name: Validate Routers & Message Processors
  hosts: rmp,r
  tags: ['setup']
  serial: 1
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
    - { role: apigee-opdk-settings-private-address }
    - { role: apigee-opdk-settings-management-server }
    - { role: apigee-opdk-settings-region }
    - { role: apigee-opdk-setup-validate }

- name: Cleanup Validate Routers & Message Processors
  hosts: rmp,r
  tags: ['cleanup']
  serial: 1
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
    - { role: apigee-opdk-settings-private-address }
    - { role: apigee-opdk-settings-management-server }
    - { role: apigee-opdk-settings-region }
    - { role: apigee-opdk-setup-validate-cleanup}
