---
- name: Setup listener
  shell: "nc -l -p {{ item }} &"
  with_items: "{{ ports }}"

- name: Validate port
  wait_for:
    port: "{{ item }}"
    timeout: 2
    host: "{{ private_address }}"
  delegate_to: "{{ hostvars[host]['private_address'] }}"
  with_items: "{{ ports }}"

