---
- name: Gathering Setup for Planet
  hosts: planet
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }

- name: Install Edge Mirror
  hosts: "{{ target_hosts }}"
  tags: ['install']
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/.apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-os-epel, tags: ['epel'] }
  - { role: apigee-opdk-shutdown-iptables, tags: ['iptables'] }
  - { role: apigee-opdk-yum-repository-proxy-config, tags: ['yum-proxy-config']}
  - { role: apigee-opdk-setup-os-minimum, tags: ['os-minimum'] }
  - { role: apigee-opdk-setup-os-sysctl, tags: ['sysctl'] }
  - { role: apigee-opdk-setup-selinux-disable, tags: ['selinux'] }
  - { role: apigee-server-restart, tags: ['restart-server'], start_check_delay: 30, when: (selinux_disabled is defined and selinux_disabled.changed) or (iptables_disabled is defined and not iptables_disabled) or (force_restart is defined and force_restart)  }
  - { role: apigee-opdk-setup-os-common, tags: ['os-common'] }
  - { role: apigee-opdk-setup-openjdk, tags: ['openjdk'], jdk_version: '1.8' }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-java-home, tags: ['java-home', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap', 'bootstrap'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap-create-archive, tags: ['bootstrap', 'create'] }

