---
- name: Expose apigee mirror web server
  tags: ['nginx']
  hosts: "{{ target_hosts }}"
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/.apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-setup-mirror-nginx, tags: ['nginx'] }
