---
- hosts: localhost
  connection: local
  vars_files:
  - repository-custom-properties.yml
  vars_prompt:
    - name: license_path
      prompt: "Enter path to license file"
      private: no

  tasks:
  - name: Copy license file in .apigee folder
    copy:
      src: '{{ license_path }}'
      dest: '{{ apigee_config}}/license.txt'
    register: status

  - name: Copy license file status report
    debug:
      var: status
