---
- name: Normalized name for public address
  set_fact:
    cacheable: yes
    public_address: '{{ inventory_hostname }}'

- block:

  - name: Update cache for public ip on AWS
    ec2_metadata_facts:
    when: ansible_ec2_public_ipv4 is not defined

  - name: Normalized name for public address on AWS
    set_fact:
      cacheable: yes
      public_address: '{{ ansible_ec2_public_ipv4 | default(inventory_hostname) }}'

  when: ansible_bios_version is defined and ansible_bios_version | search('amazon')
